@emailAuth = http://localhost:5092
@email = codyhowell44@gmail.com
@key = iNe!CGHVWBcarjGg!KcK

###
POST {{emailAuth}}/api/signin?email=codyhowell44@gmail.com
###
GET {{emailAuth}}/health
###
GET {{emailAuth}}/api/users
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
###
GET {{emailAuth}}/api/signout/codyhowell44@gmail.com
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
###
GET {{emailAuth}}/api/signout/global/codyhowell44@gmail.com
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
###
GET {{emailAuth}}/api/signin/delete/codyhowell44@gmail.com
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
###
GET {{emailAuth}}/api/user/codyhowell44@gmail.com
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}